# -*- MakeFile -*-

all: ej1 ej2 ej3 ej4 ej5 ej5recursivo ej6recursivo ej7while ej7recursivo ej7for ej8recursivo

ej1: ej1.cpp
	g++ ej1.cpp -o ej1

ej2: ej2.cpp
	g++ ej2.cpp -o ej2

ej3: ej3.cpp
	g++ ej3.cpp -o ej3

ej4: ej4.cpp
	g++ ej4.cpp -o ej4

ej5: ej5.cpp
	g++ ej5.cpp -o ej5

ej5recursivo: ej5recursivo.cpp
	g++ ej5recursivo.cpp -o ej5recursivo

ej6recursivo: ej6recursivo.cpp
	g++ ej6recursivo.cpp -o ej6recursivo

ej7while: ej7while.cpp
	g++ ej7while.cpp -o ej7while

ej7recursivo: ej7recursivo.cpp
	g++ ej7recursivo.cpp -o ej7rescursivo

ej7for: ej7for.cpp
	g++ ej7for.cpp -o ej7for

ej8recursivo: ej8recursivo.cpp
	g++ ej8recursivo.cpp -o ej8recursivo

clean:
	rm -f *.o  *.elf labo01